# Generated by Django 5.2.7 on 2025-12-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile_institutionprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
