# Generated by Django 5.2.7 on 2025-12-21 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_companyprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('contract_type', models.CharField(choices=[('stage', 'Stage'), ('alternance', 'Alternance')], default='stage', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('remote', models.BooleanField(default=False)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
